### ISSUE TITLE
极简版spring.application.strategy.zuul.original.header.ignored开关失效

### ISSUE THREAD

**Issue by grapeqin** [Nepxion/DiscoveryGuide#15]
discovery.version 6.0.5 

开关配置如下：

#当外界传值Header的时候，网关也设置并传递同名的Header，需要决定哪个Header传递到后边的服务去。如果下面开关为true，以网关设置为优先，否则以外界传值为优先。缺失则默认为true

#spring.application.strategy.zuul.header.priority=false

#当以网关设置为优先的时候，网关未配置Header，而外界配置了Header，仍旧忽略外界的Header。缺失则默认为true

spring.application.strategy.zuul.original.header.ignored=true

策略配置如下：

    <strategy>
        <version>{"discovery-yd-service-a":"1.0", "discovery-yd-service-b":"1.0"}</version>
    </strategy>

    <strategy-customization>
        <conditions type="blue-green">
            <condition id="condition1" header="#H['a'] == '1'" version-id="version-route2"/>
            <condition id="condition2" header="#H['a'] == '1' &amp;&amp; #H['b'] == '2'" version-id="version-route1"/>
        </conditions>
        <routes>
            <route id="version-route1" type="version">{"discovery-yd-service-a":"1.1", "discovery-yd-service-b":"1.1"}</route>
            <route id="version-route2" type="version">{"discovery-yd-service-a":"1.0", "discovery-yd-service-b":"1.1"}</route>
        </routes>
    </strategy-customization>

postman请求Zuul网关调用示例时，指定Header a = 1；

按照spring.application.strategy.zuul.original.header.ignored的解释，网关优先并且网关未配置header时，即使前端配置了Header也会忽略，本例应该选择默认的strategy策略路由；但经过实际测试，发现前端Header依然会让路由策略生效。postman返回结果为

zuul -> [ID=discovery-yd-service-a][P=Eureka][H=192.168.1.xx:3001][V=1.0][R=dev][E=env1][G=discovery-yd-group][TID=ae16acbdc83f22a5][SID=69939cfd6578554c] -> [ID=discovery-yd-service-b][P=Eureka][H=192.168.1.xx:4002][V=1.1][R=dev][E=common][G=discovery-yd-group][TID=ae16acbdc83f22a5][SID=433951c9bedf320e]

选择的是version-route2这个条件路由策略。

将spring.application.strategy.zuul.original.header.ignored这个开关设置为false，也是同样的结论。

**Comment by HaojunRen** [comment]
网关优先的情况下，前端传header始终不会生效，见截图
![图片](https://user-images.githubusercontent.com/42354711/86753587-c3159e00-c072-11ea-9a50-8dfc16f419f1.png)

**Comment by HaojunRen** [comment]
刚才又对这两个配置进行了测试，没有发现问题

**Comment by grapeqin** [comment]
spring.application.strategy.zuul.header.priority=true
spring.application.strategy.zuul.original.header.ignored=true
![image](https://user-images.githubusercontent.com/6265178/86885708-4e04a000-c128-11ea-91ca-7b4fde082a7a.png)

![image](https://user-images.githubusercontent.com/6265178/86885739-5eb51600-c128-11ea-92fa-14d59a76f4e2.png)

我的步骤是这样：
1、设置以网关配置优先
2、在网关中设置 header key="n-d-version" value="1.0"
3、postman在前端发送请求的时候不传n-d-version这个header

按照我的理解，以网关设置优先，请求的结果应该是1.0版本的这个链路；但实际上这个网关设置没有生效，链路是以随机的形式选择服务版本的。是不是我对这个网关内设置同名header的理解有误，还请指教。

**Comment by HaojunRen** [comment]
你的xml格式不正确的
网关上的配置格式是：
<?xml version="1.0" encoding="UTF-8"?>
<rule>
    <strategy>
        <version>1.0</version>
    </strategy>
</rule>

Postman上传递的格式是：
n-d-version=1.0

**Comment by grapeqin** [comment]
感谢大佬的指导，我将示例项目全部重新启动后，参考文档跑了一遍，现在控制参数能按照预期运行了。
