### ISSUE TITLE
采用redis作为简易注册中心时，与项目已有的spring-data-redis的配置冲突了

### ISSUE THREAD

**Issue by grapeqin** [Nepxion/DiscoveryGuide#17]

**Comment by grapeqin** [comment]
我们一个老项目，没有用配置中心，但现在想接入Discovery的灰度功能，打算直接用redis作为配置中心，但看了下，目前discovery-plugin-config-center-starter-redis 采用的是spring-data-redis默认的配置，刚好项目里面有几个服务配置的spring.redis.host和spring.redis.port 不一致。这个时候就没有办法统一注册中心了。我看了下源码，请问除了自己基于源码单独定义一套其他前缀（比如discoveryconfig.redis）配置中心外。Discovery项目针对这种场景是否有对应的解决方案。

**Comment by HaojunRen** [comment]
请自行统一，改源码

**Comment by grapeqin** [comment]
OK，谢谢
