### ISSUE TITLE
规则更新优化

### ISSUE THREAD

**Issue by beesman182** [Nepxion/DiscoveryGuide#20]
···
<?xml version="1.0" encoding="UTF-8"?>
<rule>
    
    <strategy>
        <version>{"discovery-guide-service-a":"1.0", "discovery-guide-service-b":"1.0"}</version>
    </strategy>

    
    <strategy-customization>
        
        
        <conditions type="gray">
            <condition id="condition1" header="#H['a'] == '1'" version-id="version-route1=10;version-route2=90"/>
            <condition id="condition2" header="#H['a'] == '1' && #H['b'] == '2'" version-id="version-route1=85;version-route2=15"/>
            <condition id="condition3" version-id="version-route1=95;version-route2=5"/>
        </conditions>

        <routes>
            <route id="version-route1" type="version">{"discovery-guide-service-a":"1.0", "discovery-guide-service-b":"1.0"}</route>
            <route id="version-route2" type="version">{"discovery-guide-service-a":"1.1", "discovery-guide-service-b":"1.1"}</route>
        </routes>
    </strategy-customization>
</rule>
···

更新配置的时候
http://localhost:6001/console/remote-config/update
‘’‘  **&&** ‘’‘ 是错误的， 应该用
`&amp;&amp; `
但还是更新到远程配置中心，在微服务端拉取配置的时候，在微服务端报了配置文件错误。

**Comment by HaojunRen** [comment]
这个在文档里特意强调过，需要仔细，因为md文档里不能实现反转义符，你看到的依旧还是&&

**Comment by HaojunRen** [comment]
后面是否都解决了？
