### ISSUE TITLE
service启动不了

### ISSUE THREAD

**Issue by shenzhuan** [Nepxion/DiscoveryGuide#21]
DiscoveryGuideServiceA1 类 以下类 找不到
import com.nepxion.discovery.plugin.strategy.service.filter.ServiceStrategyRouteFilter;
import com.nepxion.discovery.plugin.strategy.service.monitor.ServiceStrategyMonitorAdapter;
import com.nepxion.discovery.plugin.strategy.service.sentinel.adapter.ServiceSentinelRequestOriginAdapter;
 暂时删除后 启动页失败
Description:

Field strategyContextHolder in com.nepxion.discovery.plugin.strategy.aop.AbstractStrategyInterceptor required a bean of type 'com.nepxion.discovery.plugin.strategy.context.StrategyContextHolder' that could not be found.

The injection point has the following annotations:

**Comment by HaojunRen** [comment]
请不要改动任何代码，跑一下

**Comment by shenzhuan** [comment]
我刚下载的master的代码 什么都没有改

DiscoveryGuideServiceA1 类 以下类 找不到
import com.nepxion.discovery.plugin.strategy.service.filter.ServiceStrategyRouteFilter;
import com.nepxion.discovery.plugin.strategy.service.monitor.ServiceStrategyMonitorAdapter;
import com.nepxion.discovery.plugin.strategy.service.sentinel.adapter.ServiceSentinelRequestOriginAdapter;

**Comment by shenzhuan** [comment]
admin也启动不了
Description:

Parameter 0 of method loadBalancerWebClientBuilderBeanPostProcessor in org.springframework.cloud.client.loadbalancer.reactive.LoadBalancerBeanPostProcessorAutoConfiguration required a bean of type 'org.springframework.cloud.client.loadbalancer.reactive.DeferringLoadBalancerExchangeFilterFunction' that could not be found.


Action:

Consider defining a bean of type 'org.springframework.cloud.client.loadbalancer.reactive.DeferringLoadBalancerExchangeFilterFunction' in your configuration.

**Comment by HaojunRen** [comment]
你运行的master只支持Spring Cloud 2020，Spring Cloud Alibaba还未兼容，所以运行不起来，请切换到6.x.x分支
