### ISSUE TITLE
拉最新的代码跑不起

### ISSUE THREAD

**Issue by lizhichao999** [Nepxion/DiscoveryGuide#6]
import com.google.common.collect.ImmutableMap;
import com.nepxion.discovery.common.constant.DiscoveryConstant;
import com.nepxion.discovery.plugin.strategy.service.tracer.DefaultServiceStrategyTracer;
import com.nepxion.discovery.plugin.strategy.service.tracer.ServiceStrategyTracerInterceptor;
**import com.nepxion.discovery.plugin.strategy.tracer.StrategyTracerContext;**

// 自定义调用链和灰度调用链输出到日志和Opentracing
public class MyServiceStrategyTracer extends DefaultServiceStrategyTracer {
    private static final Logger LOG = LoggerFactory.getLogger(MyServiceStrategyTracer.class);

找不到 StrategyTracerContext

**Comment by HaojunRen** [comment]
请引入源码工程

**Comment by lizhichao999** [comment]
import com.nepxion.discovery.plugin.strategy.tracer.StrategyTracerContext; 的确是没找到这个类，这个类在那个工程里面

**Comment by lizhichao999** [comment]
> 请引入源码工程

import com.nepxion.discovery.plugin.strategy.tracer.StrategyTracerContext;

**Comment by lizhichao999** [comment]
> 请引入源码工程

import com.nepxion.discovery.plugin.strategy.tracer.StrategyTracerContext; 的确是没找到这个类，这个类在那个工程里面

**Comment by HaojunRen** [comment]
下载tmaster最新的代码 https://github.com/Nepxion/Discovery。目前5.5.0还没发版
